# Generated by Django 3.0.5 on 2020-05-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('painter', 'painter'), ('none', 'none'), ('plumber', 'plumber'), ('cleaner', 'cleaner')], default='none', max_length=10),
        ),
    ]
