# Generated by Django 3.0.5 on 2020-05-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200524_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('cleaner', 'cleaner'), ('none', 'none'), ('painter', 'painter'), ('plumber', 'plumber')], default='none', max_length=10),
        ),
    ]
