# Generated by Django 3.0.5 on 2020-05-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200524_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('plumber', 'plumber'), ('cleaner', 'cleaner'), ('painter', 'painter'), ('none', 'none')], default='none', max_length=10),
        ),
    ]
