# Generated by Django 3.0.5 on 2020-05-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200524_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('plumber', 'plumber'), ('none', 'none'), ('cleaner', 'cleaner'), ('painter', 'painter')], default='none', max_length=10),
        ),
    ]
