# Generated by Django 3.0.5 on 2020-05-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200524_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('none', 'none'), ('painter', 'painter'), ('cleaner', 'cleaner'), ('plumber', 'plumber')], default='none', max_length=10),
        ),
    ]
