# Generated by Django 3.0.5 on 2020-05-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200526_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('cleaner', 'cleaner'), ('painter', 'painter'), ('none', 'none'), ('plumber', 'plumber')], default='none', max_length=10),
        ),
    ]
