# Generated by Django 3.0.5 on 2020-05-24 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tower', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('clean rooms', 'rooms'), ('clean bathrooms', 'bathrooms'), ('none', 'none'), ('testing pipes', 'testing'), ('painting', 'painting'), ('clean stairs', 'stairs'), ('fiting pipes', 'fitting')], max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='operation',
            name='type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='tower.Operation_type'),
            preserve_default=False,
        ),
    ]
