# Generated by Django 3.0.5 on 2020-05-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower', '0002_auto_20200524_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation_type',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
