# Generated by Django 3.0.5 on 2020-05-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower', '0003_auto_20200524_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation_type',
            name='allowed',
            field=models.CharField(choices=[('cleaner', 'cleaner'), ('plumber', 'plumber'), ('painter', 'painter')], default='painter', max_length=30),
            preserve_default=False,
        ),
    ]
