# Generated by Django 3.0.5 on 2020-05-24 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tower', '0004_operation_type_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='foreman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='level',
            name='reports',
            field=models.ManyToManyField(blank=True, to='tower.Report'),
        ),
        migrations.AlterField(
            model_name='operation_type',
            name='allowed',
            field=models.CharField(choices=[('painter', 'painter'), ('plumber', 'plumber'), ('cleaner', 'cleaner')], max_length=30),
        ),
    ]
