# Generated by Django 3.0.5 on 2020-05-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tower', '0008_auto_20200526_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='operation_type',
            name='allowed',
            field=models.CharField(choices=[('painter', 'painter'), ('cleaner', 'cleaner'), ('plumber', 'plumber')], max_length=30),
        ),
    ]
