# Generated by Django 3.0.5 on 2020-05-27 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tower', '0009_auto_20200526_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='reports',
        ),
        migrations.AddField(
            model_name='report',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tower.Level'),
        ),
        migrations.AlterField(
            model_name='operation_type',
            name='allowed',
            field=models.CharField(choices=[('plumber', 'plumber'), ('painter', 'painter'), ('cleaner', 'cleaner')], max_length=30),
        ),
    ]
